---
- name: Ensure dependencies are present.
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - python3-debian
      - gnupg2
    state: present

- name: Add nodejs GPG key
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    dest: /usr/share/keyrings/nodesource.asc
    mode: '0644'
    force: true

- name: "Add nodejs {{ nodejs_version }} ppa for apt repo"
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/nodesource.asc] https://deb.nodesource.com/node_{{ nodejs_version }} nodistro main"
    state: present
  register: node_repo

- name: Update apt cache if repo was added.
  ansible.builtin.apt: update_cache=yes
  when: node_repo is changed
  tags: ['skip_ansible_lint']

- name: Ensure Node.js and npm are installed.
  ansible.builtin.apt:
    name: "nodejs={{ nodejs_version | regex_replace('x', '') }}*"
    state: present
